on:
  workflow_dispatch:
    inputs:
      username:
        description: "Enter your username"
        required: true
        default: "user123"
      email:
        description: "Enter your email"
        required: true
        default: "user@example.com"
      role:
        description: "Select your role" # Dropdown example
        required: true
        type: choice
        options:
          - Admin
          - User
          - Guest
      newsletter:
        description: "Subscribe to newsletter (true for yes, false for no)" # Checkbox example
        required: false
        default: false

jobs:
  validate-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Inputs
        run: |
          echo "Validating inputs..."

          # Validate username
          if ! [[ "${{ github.event.inputs.username }}" =~ ^[a-zA-Z0-9]{3,15}$ ]]; then
            echo "Error: Username must be alphanumeric and between 3 to 15 characters."
            exit 1
          fi

          # Validate email format
          if ! [[ "${{ github.event.inputs.email }}" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
            echo "Error: Invalid email address format."
            exit 1
          fi

          # Validate role selection
          if [[ "${{ github.event.inputs.role }}" != "Admin" && "${{ github.event.inputs.role }}" != "User" && "${{ github.event.inputs.role }}" != "Guest" ]]; then
            echo "Error: Invalid role selected."
            exit 1
          fi

          echo "Inputs are valid."
          echo "Username: ${{ github.event.inputs.username }}"
          echo "Email: ${{ github.event.inputs.email }}"
          echo "Role: ${{ github.event.inputs.role }}"
          echo "Newsletter Subscription: ${{ github.event.inputs.newsletter }}"
